### ISSUE TITLE
Epic: As a user I want to debug node.js applications

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1540]
As a user I want to debug node.js applications so that I can easier find bugs.

It is of course possible to debug a JavaScript application with the Chrome tools. However this means to start Chrome, connect the node.js instance to Chrome etc. which is inconvenient. The Eclipse IDE already provides a debugging API, and it should be possible without too much effort to connect this to node.js and N4JS.

For that, at least the following steps need to be done:

- [ ] understand the Eclipse debugging API (https://www.eclipse.org/articles/Article-Debugger/how-to.html). Also do some research regarding the DSP (https://www.eclipse.org/community/eclipse_newsletter/2018/june/dockerandlsp.php)
- [ ] understand how to debug node.js applications (https://nodejs.org/de/docs/guides/debugging-getting-started/)
- [ ] understand the N4JS runner design (https://www.eclipse.org/n4js/design/execution.html#sec:Runners-execution)
- [ ] extend the N4JS editor to support breakpoints
- [ ] understand the debugger state model and define an N4JS debugger state machine
- [ ] connect node.js to the debugger, i.e. launch it in debug mode and control it via Eclipse (implement debugger state machine)
- [ ] use the source maps to jump to the correct location (cf. org.eclipse.n4js.transpiler.sourcemap.SourceMap, there even exists a source map viewer!)
- [ ] implement the debug model for N4JS
- [ ] connect the debug model to the debugger to actually show variables etc.

For all these steps, separate issues are to be defined. Ones such an issue is done, mark the progress in this epic. More issues may be created when more information is available.
