### ISSUE TITLE
As a user I need error message if Break-Statement is used in plain Block outside iteration or switch

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#218]
When running this error marker free code in NodeJS
```javascript
function foo() {
	LBL: {
		break;
	}
}
```

the following error is reported:
```
(SystemJS) Illegal break statement
					break;
					^^^^^
	SyntaxError: Illegal break statement
	    at Object.exports.runInThisContext (vm.js:78:16)
```

A validation adding an error marker should be added (e.g. to org.eclipse.n4js.validation.ASTStructureValidator.validateASTStructure(BreakStatement, ASTStructureDiagnosticProducer, Set<LabelledStatement>, Constraints)).

To quite the ECMAScript spec:

"
13.9.1 Static Semantics: Early Errors

BreakStatement : break ;

It is a Syntax Error if this BreakStatement is not nested, directly or indirectly (but not
crossing function boundaries), within an IterationStatement or a SwitchStatement."

We already have a check (and error message), but it seems as this is not working for the afore mentioned AST.

## Acceptance Criteria

```
function foo() {
    LBL: {
        // XPECT FIXME errors --> "break statement without enclosing iteration or case block."
        break;
    }
    while (true) {
        // This is correct! XPECT noerrors --> ""
        break;
    }
    // XPECT errors --> "break statement without enclosing iteration or case block."
    break;
    
}

foo();
```

must work.

## Hints

- have a look at the AST view
- in order to debug, run N4JS in debug mode. Unfortunately changing xtend code requires a restart. Do not simply "terminate" the runtime instance, but instead disable breakpoints and correctly quit the application

**Comment by mmews-n4** [comment]
The same is true for the following:
```javascript
function foo() {
	LBL: if (true) {
		break;
	} catch (e) {}
}
```
and
```javascript
function foo() {
	LBL: try {
		break;
	} catch (e) {}
}
```

**Comment by mor-n4** [comment]
From the ES2015 spec:

*It is a Syntax Error if this production is not nested, directly or indirectly (but not crossing function boundaries), within an IterationStatement or a SwitchStatement.*

cf. http://www.ecma-international.org/ecma-262/6.0/index.html#sec-break-statement-static-semantics-early-errors

**Comment by mor-n4** [comment]
Interestingly, in node v8.9.1 it behaves as follows:
```javascript
"use strict";

// works fine:

function declaredFunction() {
	LBL: {
		break;
	}
}

// throws exception:

(function functionExpression() {
	LBL: {
		break;
	}
});
```
Exception:
```
test.js:15
		break;
		^^^^^

SyntaxError: Illegal break statement
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by jpilgrim** [comment]
Assigned to Emira and Arda (HAW Project)

**Comment by SonKodcu** [comment]
# Problems
According to MDN, it is permitted to break a labelled block with break statement followed by the label name. _See:_ [MDN Break Statement](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/break)
```javascript
function foo() {
	LBL: {
		break LBL; // OK
	}
}
```
That is also how N4JS behaves. However, this situation contradicts the Ecmascript specification.
In our implementation, we kept to Ecmascript. Therefore, there are five failed tests.
_See:_ [Failed tests](http://projn4js.ful.informatik.haw-hamburg.de:8080/blue/organizations/jenkins/N4JSPR%2Fn4js/detail/PR-1508/3/tests/)

## TODOs

- [ ] Explore Google's behaviour
- [ ] Explore Node's behaviour
- [ ] Decision for a variant (Ecmascript or others)

## Possible solutions:

1. Adapting all failed tests to the new behavior.
2. Replacement of error messages with warning messages, when attempted to break a labelled block explicitly with brake statement followed by the label name.

**Comment by jpilgrim** [comment]
@SonKodcu Thanks for the analysis. Could you check the behavior on Chrome and Firefox. For node.js I'm pretty sure that it throws an error, could you confirm that?
 
@mor-n4 , @mmews-n4, assuming node.js and Chrome throw errors, I would suggest we got for solution 1: Adapt all failed tests to the new behavior. What would you say? Maybe we could ask our JS wizard, @dbo :-)

For that we would need to change the tests in the ECMAScript test suite, i.e., in the zip file. This is a bit annoying but worth the trouble since we do not want runtime errors which could be detected at compile time.

**Comment by SonKodcu** [comment]
@jpilgrim Both Chrome and Node.js runs the code above without any problem. But if there is no label name after break, a compiler error occurs.

**Comment by mmews-n4** [comment]
Solution one is fine for me.

**Comment by jpilgrim** [comment]
OK, then to summarize and specify the new wanted behavior:

Fact: Node.js, Chrome and Firefox are more flexible than the ECMAScript spec. The later completely disallows breaks outside loops or switch statements. The engines allow break outside loops/switch, if and only if a label is used and the label exists.

N4JS: We allow break outside loop and switch statements if and only if it is used with a label, and the label must exist in the current scope (including parent scopes).

TODO: (@SonKodcu)

- [ ] adjust validation to allow break with labels according to definition above.
- [ ] update specification
- [ ] check ECMAScript tests again, if necessary adapt failing tests

**Comment by szarnekow** [comment]
> Fact: Node.js, Chrome and Firefox are more flexible than the ECMAScript spec. The later completely disallows breaks outside loops or switch statements. 

This holds true only for the case without a label identifier. To quote the spec here

> BreakStatement:break;
It is a Syntax Error if this BreakStatement is not nested, directly or indirectly (but not crossing function boundaries), within an IterationStatement or a SwitchStatement.

So I don't see any contradiction to the spec in the behavior of Chrome, node or any other JS engine that I'm aware of.

**Comment by jpilgrim** [comment]
@szarnekow Thank you! In deed, you are right. I mixed up something. I thought that the quote from the spec is related to all kind of breaks, but only after your comment I realized that it is only for break statements without a label. Great, then everything is according to the ECMAScript spec. :-)
